def hello():
    def sl(duration):
        import time
        time.sleep(duration)
    def printr(s):
        print(s, end="\r")
    printr("H")
    sl(0.3)
    printr("He")
    sl(0.3)
    printr("Hel")
    sl(0.3)
    printr("Hell")
    sl(0.3)
    printr("Hello")
    sl(0.3)
    printr("Hello, ")
    sl(0.3)
    printr("Hello, m")
    sl(0.3)
    printr("Hello, my")
    sl(0.3)
    printr("Hello, my n")
    sl(0.3)
    printr("Hello, my na")
    sl(0.3)
    printr("Hello, my nam")
    sl(0.3)
    printr("Hello, my name ")
    sl(0.3)
    printr("Hello, my name i")
    sl(0.3)
    printr("Hello, my name is ")
    sl(0.3)
    printr("Hello, my name is T")
    sl(0.3)
    printr("Hello, my name is Th")
    sl(0.3)
    printr("Hello, my name is The")
    sl(0.3)
    printr("Hello, my name is TheT")
