def hello():
    import random
    def sl(duration):
        import time
        time.sleep(duration)
    def printr(s):
        d = round(random.uniform(0, 1), 1) #source: https://stackoverflow.com/a/49614185/9654083
        print(s, end="\r")
        sl(d)
    printr("H")
    printr("He")
    printr("Hel")
    printr("Hell")
    printr("Hello")
    printr("Hello, ")
    printr("Hello, m")
    printr("Hello, my")
    printr("Hello, my n")
    printr("Hello, my na")
    printr("Hello, my nam")
    printr("Hello, my name ")
    printr("Hello, my name i")
    printr("Hello, my name is ")
    printr("Hello, my name is T")
    printr("Hello, my name is Th")
    printr("Hello, my name is The")
    printr("Hello, my name is TheT")
    printr("Hello, my name is TheTe")
    printr("Hello, my name is TheTec")
    printr("Hello, my name is TheTech")
    printr("Hello, my name is TheTechR")
    printr("Hello, my name is TheTechRo")
    printr("Hello, my name is TheTechRob")
    printr("Hello, my name is TheTechRobo")
    printr("Hello, my name is TheTechRobo a")
    printr("Hello, my name is TheTechRobo an")
    printr("Hello, my name is TheTechRobo and ")
    printr("Hello, my name is TheTechRobo and y")
    printr("Hello, my name is TheTechRobo and yo")
    printr("Hello, my name is TheTechRobo and you")
    printr("Hello, my name is TheTechRobo and your")
    printr("Hello, my name is TheTechRobo and your c")
    printr("Hello, my name is TheTechRobo and your co")
    printr("Hello, my name is TheTechRobo and your com")
    printr("Hello, my name is TheTechRobo and your como")
    printr("Hello, my name is TheTechRobo and your com")
    printr("Hello, my name is TheTechRobo and your comp")
    printr("Hello, my name is TheTechRobo and your compu")
    printr("Hello, my name is TheTechRobo and your comput")
    printr("Hello, my name is TheTechRobo and your compute")
    printr("Hello, my name is TheTechRobo and your computer")
    printr("Hello, my name is TheTechRobo and your computer h")
    printr("Hello, my name is TheTechRobo and your computer ha")
    printr("Hello, my name is TheTechRobo and your computer has")
    printr("Hello, my name is TheTechRobo and your computer has b")
    printr("Hello, my name is TheTechRobo and your computer has be")
    printr("Hello, my name is TheTechRobo and your computer has bee")
    printr("Hello, my name is TheTechRobo and your computer has been ")
    printr("Hello, my name is TheTechRobo and your computer has been i")
    printr("Hello, my name is TheTechRobo and your computer has been in")
    printr("Hello, my name is TheTechRobo and your computer has been inv")
    printr("Hello, my name is TheTechRobo and your computer has been invo")
    printr("Hello, my name is TheTechRobo and your computer has been invol")
    printr("Hello, my name is TheTechRobo and your computer has been involu")
    printr("Hello, my name is TheTechRobo and your computer has been involun")
    printr("Hello, my name is TheTechRobo and your computer has been involunt")
    printr("Hello, my name is TheTechRobo and your computer has been involunta")
    printr("Hello, my name is TheTechRobo and your computer has been involuntar")
    printr("Hello, my name is TheTechRobo and your computer has been involuntari")
    printr("Hello, my name is TheTechRobo and your computer has been involuntaril")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily ")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily s")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily se")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily sele")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selec")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily select")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selecte")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected ")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected a")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a t")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a te")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a tes")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a test")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testb")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbe")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed f")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed fo")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for m")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my n")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my ne")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new O")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS n")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS na")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS nam")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS name")
    printr("Hello, my name is TheTechRobo and your computer has been involuntarily selected as a testbed for my new OS named")
    print()
