from random import randint as random
import time
from func import *
hello()
def RandomKbps():
    hi = random(0, 4242)
    return hi
time.sleep(1)
print("Starting format...", end="\r")
time.sleep(2)
print("Formatting /dev/sda0", end="\r")
time.sleep(5)
print("Done.               ", end="\r")
time.sleep(0.9)
print("OS v.0.0.1-nightly is installing...", end="\r")
time.sleep(0.7)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...       ", end="\r")
time.sleep(0.3)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...       ", end="\r")
time.sleep(0.3)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps....        ", end="\r")
time.sleep(0.3)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...           ", end="\r")
time.sleep(0.3)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...             ", end="\r")
time.sleep(0.3)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...                 ", end="\r")
time.sleep(0.5)
print("Copying file /Kernel... (30MB) ", RandomKbps(), " KBps...                    ", end="\r")
time.sleep(0.5)
print("Verifying file /Kernel... (30MB) 1.3 MBps... Please wait.", end="\r")
time.sleep(0.3)
print("Verifying file /Kernel... (30MB) 846 KBps...", end="\r")
time.sleep(0.2)
print("Verifying file /Kernel... (30MB) ", RandomKbps(), " KBps...", end="\r")
time.sleep(0.5)
print("Verifying file /Kernel... (30MB) 1.8 MBps...", end="\r")
time.sleep(0.5)
print("Verifying file /Kernel... (30MB) 1.9 MBps...", end="\r")
time.sleep(0.5)
print("Copying file /README... (1KB) ", RandomKbps(), " KBps... Please wait.", end="\r")
time.sleep(0.4)
print("Verifying file /README... (1KB) 1.6 MBps... Please wait.    ", end="\r")
time.sleep(0.2)
print("Copying file /term... (21MB) 3938 KBps... Please wait.       ", end="\r")
time.sleep(0.2)
print("Copying file /term... (21MB) 2.4 MBps... Please wait.  ", end="\r")
time.sleep(0.8)
print("Copying file /Interface/default... (0Bytes) 0 Bytes per second... Please wait.", end="\r")
time.sleep(0.4)
print("Done!                                                                             ", end="\r")
print()
